server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_service_db
    username: root
    password: interOP@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
aws:
  kinesis:
    region: us-east
    profile: default
    stream-name: test-stream

localstack:
  kinesis:
    endpoint: http://localhost:4566